type Notes = {
    alphabetic: string; // Représentation alphabétique de la note (ex: C4, D#5)
    solmization: string; // Représentation en solmisation (ex: Do, Ré#, Mi)
    octave: number; // Octave de la note
};

enum AlphabeticNote {
    C = "C",
    CSharp = "C#/Db",
    D = "D",
    DSharp = "D#/Eb",
    E = "E",
    F = "F",
    FSharp = "F#/Gb",
    G = "G",
    GSharp = "G#/Ab",
    A = "A",
    ASharp = "A#/Bb",
    B = "B",
}

enum SolmizationNote {
    Do = "Do",
    DoSharp = "Do#",
    Ré = "Ré",
    RéSharp = "Ré#",
    Mi = "Mi",
    Fa = "Fa",
    FaSharp = "Fa#",
    Sol = "Sol",
    SolSharp = "Sol#",
    La = "La",
    LaSharp = "La#",
    Si = "Si",
}

export const NOTES: Map<number, Notes> = new Map([
    [16.35, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 0 }],
    [17.32, { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 0 }],
    [18.35, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 0 }],
    [19.45, { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 0 }],
    [20.6, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 0 }],
    [21.83, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 0 }],
    [23.12, { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 0 }],
    [24.5, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 0 }],
    [
        25.96,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 0 },
    ],
    [27.5, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 0 }],
    [29.14, { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 0 }],
    [30.87, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 0 }],
    [32.7, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 1 }],
    [34.65, { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 1 }],
    [36.71, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 1 }],
    [38.89, { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 1 }],
    [41.2, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 1 }],
    [43.65, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 1 }],
    [46.25, { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 1 }],
    [49.0, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 1 }],
    [
        51.91,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 1 },
    ],
    [55.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 1 }],
    [58.27, { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 1 }],
    [61.74, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 1 }],
    [65.41, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 2 }],
    [69.3, { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 2 }],
    [73.42, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 2 }],
    [77.78, { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 2 }],
    [82.41, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 2 }],
    [87.31, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 2 }],
    [92.5, { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 2 }],
    [98.0, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 2 }],
    [
        103.83,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 2 },
    ],
    [110.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 2 }],
    [
        116.54,
        { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 2 },
    ],
    [123.47, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 2 }],
    [130.81, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 3 }],
    [
        138.59,
        { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 3 },
    ],
    [146.83, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 3 }],
    [
        155.56,
        { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 3 },
    ],
    [164.81, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 3 }],
    [174.61, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 3 }],
    [185.0, { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 3 }],
    [196.0, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 3 }],
    [
        207.65,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 3 },
    ],
    [220.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 3 }],
    [
        233.08,
        { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 3 },
    ],
    [246.94, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 3 }],
    [261.63, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 4 }],
    [
        277.18,
        { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 4 },
    ],
    [293.66, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 4 }],
    [
        311.13,
        { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 4 },
    ],
    [329.63, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 4 }],
    [349.23, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 4 }],
    [
        369.99,
        { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 4 },
    ],
    [392.0, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 4 }],
    [
        415.3,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 4 },
    ],
    [440.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 4 }],
    [
        466.16,
        { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 4 },
    ],
    [493.88, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 4 }],
    [523.25, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 5 }],
    [
        554.37,
        { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 5 },
    ],
    [587.33, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 5 }],
    [
        622.25,
        { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 5 },
    ],
    [659.25, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 5 }],
    [698.46, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 5 }],
    [
        739.99,
        { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 5 },
    ],
    [783.99, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 5 }],
    [
        830.61,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 5 },
    ],
    [880.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 5 }],
    [
        932.33,
        { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 5 },
    ],
    [987.77, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 5 }],
    [1046.5, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 6 }],
    [
        1108.73,
        { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 6 },
    ],
    [1174.66, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 6 }],
    [
        1244.51,
        { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 6 },
    ],
    [1318.51, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 6 }],
    [1396.91, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 6 }],
    [
        1479.98,
        { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 6 },
    ],
    [1567.98, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 6 }],
    [
        1661.22,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 6 },
    ],
    [1760.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 6 }],
    [
        1864.66,
        { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 6 },
    ],
    [1975.53, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 6 }],
    [2093.0, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 7 }],
    [
        2217.46,
        { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 7 },
    ],
    [2349.32, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 7 }],
    [
        2489.02,
        { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 7 },
    ],
    [2637.02, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 7 }],
    [2793.83, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 7 }],
    [
        2959.96,
        { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 7 },
    ],
    [3135.96, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 7 }],
    [
        3322.44,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 7 },
    ],
    [3520.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 7 }],
    [
        3729.31,
        { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 7 },
    ],
    [3951.07, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 7 }],
    [4186.01, { alphabetic: AlphabeticNote.C, solmization: SolmizationNote.Do, octave: 8 }],
    [
        4434.92,
        { alphabetic: AlphabeticNote.CSharp, solmization: SolmizationNote.DoSharp, octave: 8 },
    ],
    [4698.63, { alphabetic: AlphabeticNote.D, solmization: SolmizationNote.Ré, octave: 8 }],
    [
        4978.03,
        { alphabetic: AlphabeticNote.DSharp, solmization: SolmizationNote.RéSharp, octave: 8 },
    ],
    [5274.04, { alphabetic: AlphabeticNote.E, solmization: SolmizationNote.Mi, octave: 8 }],
    [5587.65, { alphabetic: AlphabeticNote.F, solmization: SolmizationNote.Fa, octave: 8 }],
    [
        5919.91,
        { alphabetic: AlphabeticNote.FSharp, solmization: SolmizationNote.FaSharp, octave: 8 },
    ],
    [6271.93, { alphabetic: AlphabeticNote.G, solmization: SolmizationNote.Sol, octave: 8 }],
    [
        6644.88,
        { alphabetic: AlphabeticNote.GSharp, solmization: SolmizationNote.SolSharp, octave: 8 },
    ],
    [7040.0, { alphabetic: AlphabeticNote.A, solmization: SolmizationNote.La, octave: 8 }],
    [
        7458.62,
        { alphabetic: AlphabeticNote.ASharp, solmization: SolmizationNote.LaSharp, octave: 8 },
    ],
    [7902.13, { alphabetic: AlphabeticNote.B, solmization: SolmizationNote.Si, octave: 8 }],
]);
