export class Notes {
    alphabetic: string; // Représentation alphabétique de la note (ex: C4, D#5)
    solmization: string; // Représentation en solmisation (ex: Do, Ré#, Mi)
    octave: number; // Octave de la note

    constructor(alphabetic: string, solmization: string, octave: number) {
        this.alphabetic = alphabetic;
        this.solmization = solmization;
        this.octave = octave;
    }

    isSharp = (): boolean => {
        return this.alphabetic.includes("#") || this.alphabetic.includes("b");
    };
}

enum AlphabeticNote {
    C = "C",
    CSharp = "C#/Db",
    D = "D",
    DSharp = "D#/Eb",
    E = "E",
    F = "F",
    FSharp = "F#/Gb",
    G = "G",
    GSharp = "G#/Ab",
    A = "A",
    ASharp = "A#/Bb",
    B = "B",
}

enum SolmizationNote {
    Do = "Do",
    DoSharp = "Do#",
    Ré = "Ré",
    RéSharp = "Ré#",
    Mi = "Mi",
    Fa = "Fa",
    FaSharp = "Fa#",
    Sol = "Sol",
    SolSharp = "Sol#",
    La = "La",
    LaSharp = "La#",
    Si = "Si",
}

export const NOTES: Map<number, Notes> = new Map([
    [16.35, new Notes(AlphabeticNote.C, SolmizationNote.Do, 0)],
    [17.32, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 0)],
    [18.35, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 0)],
    [19.45, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 0)],
    [20.6, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 0)],
    [21.83, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 0)],
    [23.12, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 0)],
    [24.5, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 0)],
    [25.96, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 0)],
    [27.5, new Notes(AlphabeticNote.A, SolmizationNote.La, 0)],
    [29.14, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 0)],
    [30.87, new Notes(AlphabeticNote.B, SolmizationNote.Si, 0)],
    [32.7, new Notes(AlphabeticNote.C, SolmizationNote.Do, 1)],
    [34.65, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 1)],
    [36.71, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 1)],
    [38.89, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 1)],
    [41.2, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 1)],
    [43.65, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 1)],
    [46.25, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 1)],
    [49.0, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 1)],
    [51.91, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 1)],
    [55.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 1)],
    [58.27, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 1)],
    [61.74, new Notes(AlphabeticNote.B, SolmizationNote.Si, 1)],
    [65.41, new Notes(AlphabeticNote.C, SolmizationNote.Do, 2)],
    [69.3, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 2)],
    [73.42, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 2)],
    [77.78, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 2)],
    [82.41, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 2)],
    [87.31, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 2)],
    [92.5, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 2)],
    [98.0, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 2)],
    [103.83, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 2)],
    [110.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 2)],
    [116.54, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 2)],
    [123.47, new Notes(AlphabeticNote.B, SolmizationNote.Si, 2)],
    [130.81, new Notes(AlphabeticNote.C, SolmizationNote.Do, 3)],
    [138.59, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 3)],
    [146.83, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 3)],
    [155.56, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 3)],
    [164.81, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 3)],
    [174.61, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 3)],
    [185.0, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 3)],
    [196.0, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 3)],
    [207.65, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 3)],
    [220.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 3)],
    [233.08, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 3)],
    [246.94, new Notes(AlphabeticNote.B, SolmizationNote.Si, 3)],
    [261.63, new Notes(AlphabeticNote.C, SolmizationNote.Do, 4)],
    [277.18, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 4)],
    [293.66, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 4)],
    [311.13, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 4)],
    [329.63, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 4)],
    [349.23, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 4)],
    [369.99, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 4)],
    [392.0, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 4)],
    [415.3, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 4)],
    [440.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 4)],
    [466.16, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 4)],
    [493.88, new Notes(AlphabeticNote.B, SolmizationNote.Si, 4)],
    [523.25, new Notes(AlphabeticNote.C, SolmizationNote.Do, 5)],
    [554.37, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 5)],
    [587.33, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 5)],
    [622.25, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 5)],
    [659.25, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 5)],
    [698.46, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 5)],
    [739.99, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 5)],
    [783.99, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 5)],
    [830.61, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 5)],
    [880.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 5)],
    [932.33, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 5)],
    [987.77, new Notes(AlphabeticNote.B, SolmizationNote.Si, 5)],
    [1046.5, new Notes(AlphabeticNote.C, SolmizationNote.Do, 6)],
    [1108.73, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 6)],
    [1174.66, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 6)],
    [1244.51, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 6)],
    [1318.51, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 6)],
    [1396.91, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 6)],
    [1479.98, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 6)],
    [1567.98, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 6)],
    [1661.22, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 6)],
    [1760.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 6)],
    [1864.66, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 6)],
    [1975.53, new Notes(AlphabeticNote.B, SolmizationNote.Si, 6)],
    [2093.0, new Notes(AlphabeticNote.C, SolmizationNote.Do, 7)],
    [2217.46, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 7)],
    [2349.32, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 7)],
    [2489.02, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 7)],
    [2637.02, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 7)],
    [2793.83, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 7)],
    [2959.96, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 7)],
    [3135.96, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 7)],
    [3322.44, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 7)],
    [3520.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 7)],
    [3729.31, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 7)],
    [3951.07, new Notes(AlphabeticNote.B, SolmizationNote.Si, 7)],
    [4186.01, new Notes(AlphabeticNote.C, SolmizationNote.Do, 8)],
    [4434.92, new Notes(AlphabeticNote.CSharp, SolmizationNote.DoSharp, 8)],
    [4698.63, new Notes(AlphabeticNote.D, SolmizationNote.Ré, 8)],
    [4978.03, new Notes(AlphabeticNote.DSharp, SolmizationNote.RéSharp, 8)],
    [5274.04, new Notes(AlphabeticNote.E, SolmizationNote.Mi, 8)],
    [5587.65, new Notes(AlphabeticNote.F, SolmizationNote.Fa, 8)],
    [5919.91, new Notes(AlphabeticNote.FSharp, SolmizationNote.FaSharp, 8)],
    [6271.93, new Notes(AlphabeticNote.G, SolmizationNote.Sol, 8)],
    [6644.88, new Notes(AlphabeticNote.GSharp, SolmizationNote.SolSharp, 8)],
    [7040.0, new Notes(AlphabeticNote.A, SolmizationNote.La, 8)],
    [7458.62, new Notes(AlphabeticNote.ASharp, SolmizationNote.LaSharp, 8)],
    [7902.13, new Notes(AlphabeticNote.B, SolmizationNote.Si, 8)],
]);
